[package]
name = "allergen-assessment"
version = "0.1.0"
authors = ["Emil Ohlsson <emil@kottland.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
